#!/usr/bin/env python3
"""
Generate lookup table for 8-bit sparsity patterns.
For each of 256 possible patterns, precompute:
  - count: number of set bits
  - offsets: indices of set bits
"""

def generate_pattern_lut():
    lut_entries = []

    for pattern in range(256):
        # Find set bits
        offsets = []
        for i in range(8):
            if pattern & (1 << i):
                offsets.append(i)

        count = len(offsets)
        # Pad offsets to length 8 with zeros
        offsets_padded = offsets + [0] * (8 - count)

        lut_entries.append((count, offsets_padded))

    return lut_entries

def write_header(lut_entries, output_path):
    with open(output_path, 'w') as f:
        f.write("#pragma once\n\n")
        f.write("/*\n")
        f.write(" * Precomputed lookup table for 8-bit sparsity patterns\n")
        f.write(" * \n")
        f.write(" * For each of 256 possible patterns (0x00 to 0xFF):\n")
        f.write(" *   - count: number of set bits (__popc equivalent)\n")
        f.write(" *   - offsets[8]: indices of set bits (0-7)\n")
        f.write(" * \n")
        f.write(" * Generated by scripts/generate_pattern_lut.py\n")
        f.write(" */\n\n")

        f.write("struct PatternLUT {\n")
        f.write("    uint8_t count;\n")
        f.write("    uint8_t offsets[8];\n")
        f.write("};\n\n")

        f.write("// Constant memory for fast access (1.25 KB)\n")
        f.write("__device__ __constant__ PatternLUT PATTERN_LUT_BK8[256] = {\n")

        for i, (count, offsets) in enumerate(lut_entries):
            offsets_str = ", ".join(map(str, offsets))
            f.write(f"    {{{count}, {{{offsets_str}}}}}")

            if i < 255:
                f.write(",")

            # Add comment every 16 entries for readability
            if i % 16 == 0:
                f.write(f"  // 0x{i:02X}")

            f.write("\n")

        f.write("};\n")

if __name__ == "__main__":
    lut_entries = generate_pattern_lut()
    output_path = "../include/pattern_lut.cuh"
    write_header(lut_entries, output_path)
    print(f"Generated {output_path} with {len(lut_entries)} entries")
